# fly.toml file generated for wandering-shadow-5013 on 2022-11-02T23:40:06-05:00

app = "wandering-shadow-5013"

[deploy]
  release_command = "npm run build"

[env]
  PORT = "8080"

[processes]
  app = "node app.js"

[[services]]
  processes = ["app"] # this service only applies to the web process
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []



